name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git    
        uses: actions/checkout@v4
      - name: update apt
        run: |
          sudo apt-get update && sudo apt-get install -y dpkg-dev
      - name : get arch
        run: |
          uname -r 
      - name: extra code
        run : |
          dpkg-source -x *dsc
      - name: download build dep
        run: |
          ls
          sudo apt-get build-dep -y ./*/
      - name: build package
        run: |
          cd ./*/ && dpkg-buildpackage -us -uc -b 
      - name: upload debs
        uses: actions/upload-artifact@v3
        with:
          name: debs
          path: |
            *deb
            *udeb
